### PR TITLE
MODULE_SPEECH: Adding macOS say backend

### PR DESCRIPTION
**Pull request by njoubert**
This is a pretty simple commit.

It adds the 'say' backend, the default text-to-speech engine on mac.

It also adds a skeleton command line command to test the speech engine.

### CODE REVIEW

**Comment by peterbarker** [comment]
@bugobliterator Any chance you could test this?

**Comment by bugobliterator** [comment]
@peterbarker ok

**Comment by bugobliterator** [comment]
@peterbarker Tested and works beautifully!

**Comment by peterbarker** [comment]
Thanks @bugobliterator!

I've just tested this on Linux, and works :-)

Happy to merge as is, but I think it would be nice if the `speech` command first was modified so you could say
`speech say This is a test of the emergency broadcast system`

I'm happy to make the change myself; @njoubert your thoughts?

**Comment by njoubert** [comment]
Thanks @bugobliterator !! @peterbarker totally agree, I pushed a commit with that functionality.

Zooming out a bit: We've been using qgroundcontrol's text-to-speech engine, and I keep getting requests from our test pilot for specific things he wants to hear. Rather than working on qgroundcontrol, which often crashes on my Mac, I'm going to put some effort into tailoring MAVProxy's text-to-speech module. 

Specifically, I imagine being able to select what you'd like to hear and how often from a list. I'll send another PR :)

**Comment by peterbarker** [comment]
Merged, thanks!

Suggest making bug reports against QGC; Mr Gagne is keen to have QGC working and reliable!

**Comment by njoubert** [comment]
Thanks you!

and will do!


- Dr. Niels

**Pull request merged**
