### PR TITLE
Add a GUI for showing RC and servo channels

### PR DESCRIPTION
**Pull request by stephendade**
As per the below screenshot, this adds GUI windows for showing the current values of the RC inputs and Servo outputs. Useful for debugging any issues with inputs and outputs.

It can be launched via ``rc guiin`` or ``rc guiout`` to show the RC in and Servo out windows respectively. Otherwise, there is a menu for them in the console (rc menu).

Tested in SITL.

Screenshot from 2024-02-29 16-26-42

### CODE REVIEW

**Review by peterbarker — DISMISSED** [review]
```
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/pygauge.py", line 380, in OnPaint
    dc.DrawText(drawString, textXPos, textYPos)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/pygauge.py", line 380, in OnPaint
    dc.DrawText(drawString, textXPos, textYPos)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/pygauge.py", line 380, in OnPaint
    dc.DrawText(drawString, textXPos, textYPos)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/pygauge.py", line 380, in OnPaint
    dc.DrawText(drawString, textXPos, textYPos)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
```

**Comment by stephendade** [comment]
@peterbarker -  haven't come across that error. What version of wxpython are you running? I'm running v4.2.1

**Comment by peterbarker** [comment]
> @peterbarker - haven't come across that error. What version of wxpython are you running? I'm running v4.2.1

```
>>> wx.__version__
'4.0.7'
>>> 
```

... it's OK to require a more recent version - but we should catch the problem and tell the user something useful :-)  Perhaps fail to load the module in this case?

**Comment by stephendade** [comment]
Well, this was an interesting one. According to https://discuss.wxpython.org/t/float-values-no-longer-accepted-in-wxpython-4-1-2a1-dev5259/35731 and some testing if a user is running Python 3.10+, they also need to be running wxpython 4.2.1+

I've now added in a check for this.

**Comment by tridge** [comment]
@stephendade can you also add it to a Tools/ menu on the console so users can find it?
thanks!

**Comment by stephendade** [comment]
> @stephendade can you also add it to a Tools/ menu on the console so users can find it?
thanks!

I've already got an "RC" menu in the terminal with menu items for both. Are you thinking a more generic "Tools" menu so we can add other useful things later?

**Comment by stephendade** [comment]
> add it to a Tools/ menu on the console so users can find it?

Done

**Review by tridge — APPROVED** [review]

**Pull request merged**
