### PR TITLE
Old style exceptions --> new style for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Can you rebase this ?

**Comment by cclauss** [comment]
These changes were all landed already.

**Comment by amilcarlucas** [comment]
So this turned into an empty comit after you rebased it on master ? :)

**Comment by cclauss** [comment]
Yes.

**Pull request closed without merging**
