### PR TITLE
MAVExplorer working on macOS Sierra

### PR DESCRIPTION
**Pull request by bugobliterator**
Installing Prerequisites:
* Python installed via `brew install python --framework`
* `sudo pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix`
* `brew switch readline 6.3.8`
* `sudo pip install gnureadline`
* `sudo pip install billiard`
* `sudo pip uninstall python-dateutil`
* `sudo pip install numpy pyparsing`
* Install MAVProxy using `sudo python setup.py build install`

I will continue with similar upgrade with MAVProxy as well.

### CODE REVIEW

**Comment by lvale** [comment]
```
Sparkle:~ Luis$ brew switch readline 6.3.8
Error: readline does not have a version "6.3.8" in the Cellar.
Versions available: 7.0.1, 7.0.3, 7.0.3_1
Sparkle:~ Luis$ 
```

Any suggestions ?

**Comment by davidbuzz** [comment]
> brew install python --framework

sometime later...

Warning: python: this formula has no --framework option so it will be ignored!

**Comment by davidbuzz** [comment]
Great work.  With this patch I was able to run MAVExplorer.py on OSX 10.10.5 ( Yosemite )  and load graphs. Instructions were right  except for the fact that python-dateutil actually IS required, so I re-installed it with 'sudo pip install python-dateutil'.     
examples: 
image

**Comment by davidbuzz** [comment]
this menu option crashes one of the python instances though... MAVExplorer(menu) -> Settings
image

**Comment by jmachuca77** [comment]
I had to install several other module like matplotlib and future. I had the same issue as Buzz, but it seems to be related to python not finding the --framework option.

**Comment by bugobliterator** [comment]
@peterbarker @tridge Can you have a look and see if its pullable ?

**Comment by peterbarker** [comment]
@bugobliterator @jmachuca77 I believe we avoid mentioning things like matplotlib and other dependencies in `requirements.txt` so a user can install a minimal working MAVProxy on systems where the more complex packages may not be available.  Which is why @jmachuca77 found himself installing extra packages.  I think we should probably split out MAVExplorer into a separate package at some stage to  do this properly, but we should definitely create something like a a requirements-MAVExplorer.txt to avoid people doing the "try to run it, install missing-packages, repeat" loop.  See `MAVProxy/modules/cesium/requirements.txt` for precedent there.

The readline requirement looks awfully specific/fragile.

Need to understand the problem with `--framework` question people have raised.

I haven't tested this; running it threw the obvious `No module named billiard` error on my Linux system here.  Anybody pip-installing or pip-upgrading MAVProxy on any system will find their MAVExplorer no longer working,... need to think about this problem :-)

This is awesome, BTW.  *So* many people want to run SITL on MacOS.

**Comment by davidbuzz** [comment]
The --framework problem is just a warning... it does not stop the command from concluding.

**Comment by davidbuzz** [comment]
Billiard is also a standard pip package,  available here... Peter I have  no idea why u can't install it ... https://pypi.python.org/pypi/billiard/0.3.1

**Comment by peterbarker** [comment]
On Mon, 10 Apr 2017, Buzz wrote:

> Billiard is also a standard pip package, available here... Peter I have no
> idea why u can't install it ... https://pypi.python.org/pypi/billiard/0.3.1

I didn't say I couldn't install it :-)

**Comment by jmachuca77** [comment]
The - - framework is just a warning but when you click the settings menu, thats the error you get. It complains that python is not using the framework option.

jaime@Jaimes-MacBook-Pro ~/Developer/ardupilot (wickedshell/battery-voltages) $ MAVExplorer.py 
MAV> This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.


Best regards,

Jaime Machuca Mercado
CTO | Droidika | www.Droidika.com
Mail. Jaime@Droidika.com
Tel. +52 (33) 3777 5327
Cel. +52 1 (33) 3945 3350






Este correo electrónico y cualquier archivo transmitido en él, son confidenciales y para uso exclusivo de los individuos y entidades a quienes está dirigido. Si usted no es el destinatario previsto o la persona encargada de recibirlo, y tiene por error este mensaje, queda prohibido y sin validez el uso, difusión, re-envío, reimpresión o copia. Toda oferta y/o aceptación de propuestas comerciales, celebración de contratos u otros actos tendientes a la adquisición de bienes o servicios, así como el establecimiento de cualquier clase de obligación legal para Droidika S.A. de C.V., deberá confirmarse por escrito firmado autógrafamente por funcionario competente, excepto que se cuente con un contrato vigente que autorice el uso de este medio para tales fines. Si usted recibió este correo por equivocación, favor de notificar inmediatamente por este medio a su remitente, y después borrarlo de su correo

**Comment by bugobliterator** [comment]
@jmachuca77 Are you getting the error you just mentioned? I think it depends on machine to machine you probably get the framework error when you are on Sierra but not when on Yosemite. Can you let me know more details abt your system.

@peterbarker I will give it a go on my ubuntu machine and ensure that its not breaking on it while its working for mac systems.

**Comment by stephendade** [comment]
This patch appears to break the Windows build:
capture

I noted that you're using `wxPython_Phoenix`. Note that MAVProxy is still using the previous version of wxPython (https://www.wxpython.org/download.php), so there might be some incompatibilities there.

**Comment by jmachuca77** [comment]
@bugobliterator I don't have a machine with Yosemite to test with any more. Here are the details of my current machine

Model Name:	MacBook Pro
  OS: macOS Sierra version 10.12.4
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MBP133.0226.B15
  SMC Version (system):	2.38f7

**Comment by lvale** [comment]
ANother one

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B25
  SMC Version (system):	2.19f12

**Comment by bugobliterator** [comment]
@peterbarker I have made changes so the issues on non macosx are no longer there. I have found MAVProxy and MAVExplorer working as it should on Mac OSX, Windows and Ubuntu 16.04 after this patch is applied. Please feel free to pull it into the master. 
I will also create a PR to update installation instructions for mac user post this goes to master.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by peterbarker** [comment]
@stephendade Could you test master MAVProxy on Windows, please?

@lvale Could you test on master MAVProxy on MacOSX, please?

**Comment by stephendade** [comment]
I'm away this weekend, but I'll confirm Windows compatibility when I get back next week

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by stephendade** [comment]
Confirmed working in Windows

**Pull request closed without merging**
