### PR TITLE
add nokov support

### PR DESCRIPTION
**Pull request by 15871812598**
support nokov Motion capture attitude and position.
Old PR:https://github.com/ArduPilot/MAVProxy/pull/1051

### CODE REVIEW

**Comment by 15871812598** [comment]
Remove C++ sdk library as required.

**Comment by tridge** [comment]
> Remove C++ sdk library as required.

thanks!
a README.md in the nokov directory would be nice too telling people how to install

**Comment by tridge** [comment]
@15871812598 could you squash down the commits to one commit please?

**Comment by tridge** [comment]
ping me on the mavproxy discord channel when done and I will merge

**Pull request closed without merging**
