### PR TITLE
mavproxy_adsb: make cv2 requirement optional

### LINKED ISSUE #470: ADS-B module requires cv2
When running headless or without the map module there is no requirement for cv2. As the adsb module is loaded by default the mandatory cv2 requirement should be removed. This will ensure that the adsb module can be loaded and continue to function on systems where cv2 is not installed.

### PR DESCRIPTION
**Pull request by SamuelDudley**
As the adsb module is loaded by default, imports requiring cv2 should be delayed until required (the map module is loaded). 

fixes #470

### CODE REVIEW

**Comment by amilcarlucas** [comment]
@SamuelDudley Can you rebase this?
@tridge this is a nice one, please review

**Comment by SamuelDudley** [comment]
Cleaned up but untested. Looks like OBC2018 magic is required to exercise these changes... Anyone care to try it out?

**Comment by amilcarlucas** [comment]
Thanks for rebasing

**Comment by tridge** [comment]
I've pushed a simpler implementation of this to your PR branch

**Pull request merged**
