### PR TITLE
Fix typo in MAVProxy Wifi Bridge documentation page.

### PR DESCRIPTION
**Pull request by filipsladek**

### CODE REVIEW

**Comment by peterbarker** [comment]
Please squash together the commits into a single commit.  You can use `git rebase -i master` to accomplish this.

**Comment by filipsladek** [comment]
Done.

**Comment by peterbarker** [comment]
I filled out the commit message a little based on this PR title and pushed it in.  Thanks!

**Comment by amilcarlucas** [comment]
Thanks

**Pull request merged**
