### PR TITLE
chat: Changed longitude is "lat" to longitude is "lon"

### PR DESCRIPTION
**Pull request by ShashwathD**
Previously said that lat was short for longitude, but I changed it to lon, which may fix some problems with the assistant when it comes to certain prompts from the user.

### CODE REVIEW

**Review by rmackay9 — COMMENTED** [review]
Thanks very much for this!

One small thing is that the commit message should be prefixed with "chat:".  We normally add a prefix of the subsystem (or directory) that has been changed because it makes backporting easier.  If you have a [peek at our recent commit list](https://github.com/ArduPilot/MAVProxy/commits/master/) you'll see they all have a prefix

If you're not familiar with how to fix the commit I could do it for you

Thanks again!

**Comment by ShashwathD** [comment]
I’m not quite familiar with fixing commits so it would be great if you
could do it for me.

Thanks,
Shashwath

**Comment by ShashwathD** [comment]
I added the chat: at the start, so should it work now?

**Comment by rmackay9** [comment]
Hi @ShashwathD,

Thanks, it's not as easy as changing the PR title (which is what you've kindly updated).  It's the commit title that we need to fix

**Comment by rmackay9** [comment]
I've forced push to your branch now so this should be good to merge now, thanks!

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
