### PR TITLE
Support MAV_CMD_AIRFRAME_CONFIGURATION

### PR DESCRIPTION
**Pull request by LupusTheCanine**
Adds support for [MAV_CMD_AIRFRAME_CONFIGURATION](https://mavlink.io/en/messages/common.html#MAV_CMD_AIRFRAME_CONFIGURATION) this command controls landing gear. 
I would consider shorting "landinggear" to something shorter like "gear" as long as it is still easy to be found.

### CODE REVIEW

**Review by peterbarker — COMMENTED** [review]
Do you think we should just add a `gear` command to `mavproxy_misc.py` instead of a full-blown module?

Also, aliases (or just rename) of `up` and `down` would seem to make sense to me...

**Comment by LupusTheCanine** [comment]
I think that would be good. While I like single responsibility modules as it makes it easier to find things later it will be much more convenient to have it in misc.

`gear up` and `gear down` with `retract` and `extend` as aliases sounds good to me.

It would be good to add documentation page for misc too I think.

**Comment by peterbarker** [comment]
@LupusTheCanine looks like you committed a `mav.parm` in here :-)

Please remove that and squash everything into one commit.  Commit comment should be something like `'mavproxy_misc: add gear command for controlling landing gear"

This has been tested?

**Comment by LupusTheCanine** [comment]
I tested it with Ardupilot SITL. 
I will test with hardware (Arduplane updatetd to support the message)
May I add *.param to gitignore or should it be a separate pull request @peterbarker?

**Comment by peterbarker** [comment]
On Tue, 15 Nov 2022, Lupus the Canine wrote:

> I tested it with Ardupilot SITL.
> I will test with hardware (Arduplane updatetd to support the message)
> May I add *.param to gitignore or should it be a separate pull request @peterbarker?

I'm not sure the ignore would be accepted.

I'd suggest in this case "git add -p" would be what you wanted to use to 
get things ready to commit :-)

**Comment by LupusTheCanine** [comment]
@peterbarker 
Finished testing with Arduplane (modified to support the command).
Cleaned up and squashed.
Should be ready.

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
merged, thanks!

**Pull request merged**
