### PR TITLE
mqtt module update

### PR DESCRIPTION
**Pull request by Towflos**
I simplified the convert_to_dict function and added the option to use a username and password for authentication

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
@Towflos please squash this all into a succinct set of commits, one per logical change (or, really, just one with a good commit message.

Let me know if you need help doing this; the ArduPilot page on interactive rebase might help you, 'though: https://ardupilot.org/dev/docs/git-interactive-rebase.html

Commits should be prepended with `mavproxy_mqtt:` on the first line

**Comment by Towflos** [comment]
> @Towflos please squash this all into a succinct set of commits, one per logical change (or, really, just one with a good commit message.
> 
> Let me know if you need help doing this; the ArduPilot page on interactive rebase might help you, 'though: https://ardupilot.org/dev/docs/git-interactive-rebase.html
> 
> Commits should be prepended with `mavproxy_mqtt:` on the first line

I think I need some Help with this. I squashed all the commits into one and changed the message. Do I also need to delete the old commits?

**Comment by peterbarker** [comment]
@Towflos I just had a go at fixing this; the fixes are not trivial, and I'll probably break something.  Bit of a mess in here :-)

I suggest that you:
 - stop using your master branch for creating new code, instead use "topic branches" (google, or bits on our Wiki on git will help there)
 - take a branch of your work here (`git branch pr/mqtt-fixes-defunct master`)
 - reset your master branch to origin using `git checkout master; git  reset --hard origin/master`
 - create a new branch based on master (git checkout master; git checkout -b pr/mqtt-fixes`and do your work again on that branch, perhaps based on what's in that backup branch

Reasonably urgently we need to stop this module from using f-strings and make sure it at least compiles under Python2

f-strings seem to be awesome, just not yet in MAVProxy :-)

**Comment by peterbarker** [comment]
Ping @Towflos - are you still interested in pursuing this one?

**Comment by peterbarker** [comment]
> @peterbarker I totally forgot about this. Let me give it another try, otherwise I will close this request.

No worries, keep going...

**Pull request closed without merging**
