### PR TITLE
Improved MacOS support

### PR DESCRIPTION
**Pull request by tridge**
This generalises the multiprocessor support in MAVProxy, and fixes a number of issues on MacOS. Graphs and the map work.
The main thing that still doesn't work is the mission editor

### CODE REVIEW

**Comment by jmachuca77** [comment]
Nice to see work on OSX. Do you need testing?

**Comment by tridge** [comment]
@jmachuca77 yes please! It all works on my High Sierra MacMini, but what we need to get updated is install instructions.
I'm hoping it's just a matter of "pip install MAVProxy", but perhaps I have some modules installed that are non-standard

**Comment by jmachuca77** [comment]
Yeah, actually I did have some issues, with missing modules like HTMLParser, and then there are some issues with a module within it that I can’t find. (These are needed for the terrain module) When I launch it I get a terrain module not found and when going deeper those are the modules that are missing.



Best regards,

Jaime Machuca
CEO | Element Aero | www.element.aero <http://www.element.aero/>
Mail. jaime@element.aero <mailto:jaime@element.aero>

Off. +52 (33) 3805 4627
Cel. +52 1 (33) 3945 3350




Este correo electrónico y cualquier archivo transmitido en él, son confidenciales y para uso exclusivo de los individuos y entidades a quienes está dirigido. Si usted no es el destinatario previsto o la persona encargada de recibirlo, y tiene por error este mensaje, queda prohibido y sin validez el uso, difusión, re-envío, reimpresión o copia. Toda oferta y/o aceptación de propuestas comerciales, celebración de contratos u otros actos tendientes a la adquisición de bienes o servicios, así como el establecimiento de cualquier clase de obligación legal para Element Aero SAPI de CV, deberá confirmarse por escrito firmado autógrafamente por funcionario competente, excepto que se cuente con un contrato vigente que autorice el uso de este medio para tales fines. Si usted recibió este correo por equivocación, favor de notificar inmediatamente por este medio a su remitente, y después borrarlo de su correo

**Comment by jmachuca77** [comment]
**When loading the console:**
STABILIZE> module load console
STABILIZE> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 450, in import_package
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_console.py", line 9, in <module>
    from MAVProxy.modules.lib import wxconsole
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/lib/wxconsole.py", line 7, in <module>
    import textconsole, sys, time
ModuleNotFoundError: No module named 'textconsole'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 311, in load_module
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 453, in import_package
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_console.py", line 9, in <module>
    from MAVProxy.modules.lib import wxconsole
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/lib/wxconsole.py", line 7, in <module>
    import textconsole, sys, time
ModuleNotFoundError: No module named 'textconsole'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 450, in import_package
ModuleNotFoundError: No module named 'console'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 311, in load_module
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 453, in import_package
ModuleNotFoundError: No module named 'console'

Failed to load module: No module named 'console'. Use 'set moddebug 3' in the MAVProxy console to enable traceback

**And I can't find a module named "textconsole" with pip**

**Comment by jmachuca77** [comment]
**When loading map:**
STABILIZE> module load map
STABILIZE> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 450, in import_package
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/__init__.py", line 11, in <module>
    from MAVProxy.modules.mavproxy_map import mp_elevation
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/mp_elevation.py", line 14, in <module>
    from MAVProxy.modules.mavproxy_map import srtm
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/srtm.py", line 9, in <module>
    from HTMLParser import HTMLParser
  File "/usr/local/lib/python3.6/site-packages/HTMLParser.py", line 11, in <module>
    import markupbase
ModuleNotFoundError: No module named 'markupbase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 311, in load_module
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 453, in import_package
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/__init__.py", line 11, in <module>
    from MAVProxy.modules.mavproxy_map import mp_elevation
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/mp_elevation.py", line 14, in <module>
    from MAVProxy.modules.mavproxy_map import srtm
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/MAVProxy/modules/mavproxy_map/srtm.py", line 9, in <module>
    from HTMLParser import HTMLParser
  File "/usr/local/lib/python3.6/site-packages/HTMLParser.py", line 11, in <module>
    import markupbase
ModuleNotFoundError: No module named 'markupbase'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 450, in import_package
ModuleNotFoundError: No module named 'map'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 311, in load_module
  File "/usr/local/lib/python3.6/site-packages/MAVProxy-1.7.0-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 453, in import_package
ModuleNotFoundError: No module named 'map'

Failed to load module: No module named 'map'. Use 'set moddebug 3' in the MAVProxy console to enable traceback

**Same thing, I can't find a module named "markupbase" with pip**

**Comment by tridge** [comment]
@jmachuca77 is this with python3 or python2? I suspect its python3

**Comment by jmachuca77** [comment]
Yes python3 which is the default on OSX. I haven't seen any instructions to install another version. If that is needed we should add it somewhere

Best regards,

Jaime Machuca

**Comment by tridge** [comment]
i'm working on fixing py3 support at the moment

**Pull request merged**
