### PR TITLE
Parameditor: Categorical search of parameters

### PR DESCRIPTION
**Pull request by Akshath-Singhal**
Added categorical search of parameters with a predefined list of categories.

@tridge  Might need a work around for Flight Modes on Rover. Using only MODE displays extra parameters.

### CODE REVIEW

**Comment by Akshath-Singhal** [comment]
@tridge The second commit basically deals with the special case of modes in ROVERS. I will squash the commits once we agree on using this method. Also you might want to list the categories to be added to the dropdown menu here.

**Comment by Akshath-Singhal** [comment]
@tridge Both the search key and the category complements each other now. Seems ready to be merged to me.

**Comment by tridge** [comment]
the categories work, but I think the drop-down should only have the bit before the ':', so "PosControl" not "PosControl:VEL_,POS_,WPNAV_,RTL_"
It is also using substring searches, so the POS_ in PosControl is finding EK2_POS_I_GATE. Substring searches are great for the search box, but not good in the dropdown.
I've also noticed that the param editor is failing completely under python3 (specifically 3.6.8 on ubuntu 18.04). The module loads but doesn't display anything.
I also see some bugs by running flake8 over the code. For example:

MAVProxy/modules/mavproxy_paramedit/param_editor.py:219:12: F821 undefined name 'ParamEditorModule'

**Comment by Akshath-Singhal** [comment]
> the categories work, but I think the drop-down should only have the bit before the ':', so "PosControl" not "PosControl:VEL_,POS_,WPNAV_,RTL_"
> It is also using substring searches, so the POS_ in PosControl is finding EK2_POS_I_GATE. Substring searches are great for the search box, but not good in the dropdown.
> I've also noticed that the param editor is failing completely under python3 (specifically 3.6.8 on ubuntu 18.04). The module loads but doesn't display anything.
> I also see some bugs by running flake8 over the code. For example:
> 
> MAVProxy/modules/mavproxy_paramedit/param_editor.py:219:12: F821 undefined name 'ParamEditorModule'

Corrected the typo in Flake8. Though it had no effect.
Python3 error was due to unbuffered I/O for /dev/null, it has been corrected.
Displays only upto ':' for category now, substring search removed from categories.

**Comment by tridge** [comment]
much better, thanks!

**Pull request merged**
