### PR TITLE
CLI Prompt changed to python-prompt-toolkit

### PR DESCRIPTION
**Pull request by stephendade**
Changed the CLI interpreter from readline to python-prompt-toolkit to increase cross-platform compatibility.
(readline was causing occasional text-disappearing in windows)

Major change for user is command completion looks a bit different now.

### CODE REVIEW

**Comment by peterbarker** [comment]
Startup fails on Linux:

```
Loaded module graph
/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.6.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py:864: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if line == "" or line.startswith('#'):
Traceback (most recent call last):
  File "/home/pbarker/.local/bin/mavproxy.py", line 4, in <module>
    __import__('pkg_resources').run_script('MAVProxy==1.6.1', 'mavproxy.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.6.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 1106, in <module>
    
  File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.6.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 864, in run_script
    
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 14: ordinal not in range(128)
```

**Comment by stephendade** [comment]
That appears to be referring to a startup script file that it's unable to parse.
Are you able to post your startup (.scr) scripts?

**Comment by peterbarker** [comment]
On Tue, 23 May 2017, Stephen wrote:

> That appears to be referring to a startup script file that it's unable to
> parse.
> Are you able to post your startup (.scr) scripts?

Pretty much tridge's .mavinit.scr with a few bits and pieces added.

pbarker@bluebottle:~/rc/flight-data/peter-250/logs/2017-05-13/flight1$ cat 
~/.mavinit.scr | perl -pe 's/[\p{IsPrint}\n]//g'

Nothing non-printable in there.

**Comment by stephendade** [comment]
From the "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 14: ordinal not in range(128)" error you had, that indicates you've got unicode characters (or, at least non-ascii) in your script file.

I've now added unicode handling for script files (based on https://stackoverflow.com/questions/11866566/how-do-i-decode-unicode-one-line-at-a-time-in-python-2-7) which should work for you. I've tested it for unicode chars in a script file and it works quite nicely.

**Comment by peterbarker** [comment]
On Wed, 24 May 2017, Stephen wrote:

> From the "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in
> position 14: ordinal not in range(128)" error you had, that indicates you've
> got unicode characters (or, at least non-ascii) in your script file.
> 
> I've now added unicode handling for script files (based onhttps://stackoverflow.com/questions/11866566/how-do-i-decode-unicode-one-li
> ne-at-a-time-in-python-2-7) which should work for you. I've tested it for
> unicode chars in a script file and it works quite nicely.

That's fixed this issue, thanks!

**Comment by peterbarker** [comment]
Another problem I notice in testing:
```
TRAINING> rtl
Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
Mode RTL
TRAINING> 
RTL> 
```
Note the incorrect "TRAINING>" prompt with the new setup.  Here's what the old code does:
```
RTL> mode training
RTL> Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
TRAINING> Mode TRAINING
```

This new prompt is really cool in a lot of respects.

It does represent a significant change in interface, however.  It would be nice to have the new interface (tab-cycles-through-possible-completions) as an interface option while preserving the existing tab-presents-all-completions interface.  Is that possible with this library?  If not, I think we should put this in anyway and people can learn the new interface!

**Comment by peterbarker** [comment]
These patches also give ArduPilot's autotest.py a very, very bad day.

**Comment by stephendade** [comment]
>It does represent a significant change in interface, however. It would be nice to have the new interface (tab-cycles-through-possible-completions) as an interface option while preserving the existing tab-presents-all-completions interface. Is that possible with this library? If not, I think we should put this in anyway and people can learn the new interface!

I've pushed a commit changing back to the older style. It's changeable between the styles, but not at runtime.

>Note the incorrect "TRAINING>" prompt with the new setup. Here's what the old code does:

That's due to the mode change confirmation from APM coming in after the new line is printed. I'll see if I can hunt down a method to dynamically re-write the prompt.

>These patches also give ArduPilot's autotest.py a very, very bad day.

Ahh, I expect autotest.py is expecting a differently formatted output. I'll wrangle with autotest.py and see what it expects and patch things to fit.

**Comment by stephendade** [comment]
>That's due to the mode change confirmation from APM coming in after the new line is printed. I'll see if I can hunt down a method to dynamically re-write the prompt.

Fixed in the latest commit

>Ahh, I expect autotest.py is expecting a differently formatted output. I'll wrangle with autotest.py and see what it expects and patch things to fit.

So, after some very painful wrangling I've discovered that autotest.py is pushing text input too fast. Such that the MAVProxy prompt can't interpret and process all the commands.

So we have 2 options:
-Patch autotest.py to add a delay when sending commands. Specifically line 253 of ./Tools/autotest/pysim/util.py from ``ret.delaybeforesend = 0`` to ``ret.delaybeforesend = 0.1``
-Add a new commandline param to MAVProxy ``--noprompt`` which tells MAVProxy to use the old readline instead of the new CLI prompt. Autotest.py would need to be patched to use this param when calling MAVProxy.

I've tested both options and either works quite nicely. The 2nd option gives less garbage in the autotest output, but does requires that MAVProxy and APM are patched at the same time.

Any preference @peterbarker and @tridge ?

**Comment by tridge** [comment]
I've been trying this and found that this breaks nsh shell support (module load nsh; nsh start)

**Comment by stephendade** [comment]
@tridge - nsh problems are fixed

**Comment by stephendade** [comment]
@peterbarker - I've fixed up the incompatibilities with APM's autotest.py

Should (hopefully) be good to merge in now :)

**Comment by amilcarlucas** [comment]
ping

**Comment by stephendade** [comment]
@amilcarlucas - It'd be great to get this merged in ... just have to get @peterbarker or @tridge to confirm they're ok with it.

**Comment by peterbarker** [comment]
I'm getting corruption in my output.  My guess is different threads printing to the console at the same time.

```
Waiting for heartbeat from tcp:127.0.0.1:5760

Init APM:Copter V3.6-Free RAM: 1310FW Ver: 12-----------------------------dev ()
 size=16384


tures
APM: APM:Copter V3.6-dev (a88e6631)
0

APM: Frame: QUAD
Mode STABILIZE
-
online system 1
72

^[[92;1R^[[92;1R^[[92;1R^[[92;1R^[[92;1R^[[92;1R^[[92;1R^[[92;1R^[[9 took 0us
APM: Calibrating barometer
Received 860 parameters
Saved 860 parameters to mav.parm
APM: Barometer calibration complete
Init Gyro^[[92;10R***
```

Signals are not propogating correctly; if running with `--gdb` and `--debug` the process isn't being killed appropriately.

The interface is also not behaving as it did in previous iterations of this PR; it doesn't appear to be doing the tab-cycles-through-options thing.  Looks like you've deliberately gone to the readline-style.... would be nice to be able to pick different interface options somehow.

**Comment by amilcarlucas** [comment]
Needs a rebase... :(

**Pull request closed without merging**
