### PR TITLE
Entire missions (and subsets of missions) can now be relocated via mouse drag.

### PR DESCRIPTION
**Pull request by mday299**
This PR allows entire missions to be moved about via the mouse.  Instructions:
1. Load mission.
2. Right click on map.
3. Use the new Mission > Drag menu item.
4. In the pop-up dialog, indicate start and end waypoint indices (works best with whole mission, but you can also move a piece of a mission).
5. Hold down middle mouse button to drag mission waypoints to new desired location.
6. Left click to complete operation and upload waypoints' new locations to aircraft.

### CODE REVIEW

**Comment by mday299** [comment]
Note this PR makes use of:

https://github.com/mavlink/mavlink/pull/366

**Comment by tridge** [comment]
hi Michael, I haven't been able to make this work on my desktop, and my laptop doesn't have a middle button.
Perhaps we should do this like ordinary WP move? Or key the drag off the left or right button? We'd need to suppress menu popups if right button, and suppress map moves if left button.

**Comment by faerietree** [comment]
As this is an open issue, maybe a solution could be to use arrow keys? Or both right and left mouse buttons simultaneously?

**Comment by mday299** [comment]
This is a very old PR.  I'm closing it.

**Pull request closed without merging**
