### PR TITLE
add page with documentation update method

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by stephendade** [comment]
Thanks! Merged

**Comment by bugobliterator** [comment]
@stephendade you might want to compile the docs, I am not sure how the deployment works, so I just made changes to rst files and tested if they result into sensible docs on my local machine.

**Comment by stephendade** [comment]
Normally I compile on my local machine and git commit the compiled files too. Need to find a batter way when I've got time :)

**Comment by bugobliterator** [comment]
@stephendade ok, so do you want me to do PR the compilation, or you can do that from your end?

**Comment by stephendade** [comment]
Just did it myself :) All good

**Pull request merged**
