### PR TITLE
modules: add bitmask modifying to param module

### PR DESCRIPTION
**Pull request by joshanne**
Adds ability to toggle, set and clear bitmask parameters.

### CODE REVIEW

**Comment by joshanne** [comment]
Example output:

### Listing Full Bitmask
```
RTL> param bitmask NTF_LED_TYPES
NTF_LED_TYPES: LED Driver Types
NTF_LED_TYPES    123079

Bitmask:
          0 [x] : Built-in LED
          1 [x] : Internal ToshibaLED
          2 [x] : External ToshibaLED
          3 [ ] : External PCA9685
          4 [ ] : Oreo LED
          5 [ ] : DroneCAN
          6 [x] : NCP5623 External
          7 [x] : NCP5623 Internal
          8 [ ] : NeoPixel
          9 [ ] : ProfiLED
         10 [ ] : Scripting
         11 [ ] : DShot
         12 [ ] : ProfiLED_SPI
         13 [x] : LP5562 External
         14 [x] :  LP5562 Internal
         15 [x] : IS31FL3195 External
         16 [x] :  IS31FL3195 Internal
         17 [ ] :  DiscreteRGB
         18 [ ] :  NeoPixelRGB
bit index is not specified
```

### Listing Individual Bitmask Fields
```
RTL> param bitmask NTF_LED_TYPES 10
NTF_LED_TYPES: LED Driver Types
NTF_LED_TYPES    123079

Bitmask:
         10 [ ] : Scripting
action is not specified - use toggle, set or clear
```

### Toggle/Set/Clear Bitmask Index
```
RTL> param bitmask NTF_LED_TYPES 10 toggle
RTL> param bitmask NTF_LED_TYPES 10 clear
RTL> param bitmask NTF_LED_TYPES 10 set
```

**Comment by joshanne** [comment]
The last commit adds autocompletion for `bitmask`

**Comment by joshanne** [comment]
> Perhaps "setbit" and "unsetbit" which takes a bit offset?

Happy to change the ordering. I wanted to be able to diagnose bits separately from the action, but if I reorder it I'd be happy to use `param bitmask setbit` the same way as `param set` - if no mask is specified then print out the bitmask decoding.

What I don't want is to accidentally trigger `param set` when `param bitmask set` is intended.

**Review by peterbarker — APPROVED** [review]
Tested here.

It would be nice to get a sanity check on the bit-offset parameter:
```
STABILIZE> param bitmask toggle LOG_BITMASK 98
STABILIZE> timeout setting LOG_BITMASK to 316912650057057350374175801344.000000
no link
link 1 down
no link
no link
```

**Comment by peterbarker** [comment]
Merged, thanks!  I've wanted this for years!

**Comment by joshanne** [comment]
> Merged, thanks!  I've wanted this for years!
> 

Happy to do a sanity check on the bit setting.

**Pull request merged**
