### PR TITLE
MAVExplorer: fix deprecated-function warning from matplotlib

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Closes #987 

@WickedShell this doesn't kill older versions AFAICT.  Can you test it fixes your problem, please?

**Review by WickedShell — COMMENTED** [review]
It looks to me like `num2date` existed as far back as at least [matplotlib 1.3.1 ](https://matplotlib.org/1.3.0/api/dates_api.html#matplotlib.dates.num2date) which would have been 2013. Do we still need the fallback path?

**Comment by peterbarker** [comment]
On Tue, 28 Dec 2021, WickedShell wrote:

> @WickedShell commented on this pull request.
> 
> It looks to me like num2date existed as far back as at least matplotlib 1.3.1 which would have been 2013. Do we still need the fallback path?

Probably not.  But this is the least likely to break any existing setups.

**Review by WickedShell — APPROVED** [review]
Fixes the issue, I still think we should drop the backwards compat path, as it shouldn't be an issue for anyone.

**Pull request merged**
