### PR TITLE
Maps: Fixed offline handling when there are no cached files

### PR DESCRIPTION
**Pull request by stephendade**
Fixed issues where there is no maps cache and the user is offline

### CODE REVIEW

**Comment by tridge** [comment]
Hi Stephen, it looks like this will put the map into offline mode if there is any error downloading any map tile. I don't see a way to get it out of offline mode again.
I think it would be better to handle the errors individually, otherwise if you have a slightly flakey internet link the map module could go offline until you restart (or reload the map module)

**Comment by stephendade** [comment]
Tridge - I've fixed up the offline/online handling. Should work now.

**Comment by tridge** [comment]
i'm seeing merge conflicts now, sorry for being slow

**Comment by stephendade** [comment]
Rebased - should all be good now

**Comment by amilcarlucas** [comment]
@tridge  conflicts are solved now

**Pull request merged**
