### PR TITLE
missionEditorFrame.py: Remove unimplemented AGL checkbox

### LINKED ISSUE #1265: Misseditor: AGL checkbox is unused
I see no trace of it being used for anything - would you accept a PR to remove it?

### PR DESCRIPTION
**Pull request by Ryanf55**
Closes #1265

This can be implemented at a later date.

### CODE REVIEW

**Comment by Ryanf55** [comment]
[Screencast from 12-15-2024 03:21:44 PM.webm](https://github.com/user-attachments/assets/8cbe1c19-d4c1-473d-b229-acc20a098d5c)

**Comment by peterbarker** [comment]
Does the checkbox ever do anything?  Why's it in the interface at all if it doesn't do anything?

**Comment by Ryanf55** [comment]
> Does the checkbox ever do anything? Why's it in the interface at all if it doesn't do anything?

No it doesn't. It wasn't hooked up.

**Comment by peterbarker** [comment]
On Sun, 15 Dec 2024, Ryan wrote:

> No it doesn't. It wasn't hooked up.

.... so maybe just comment out the code which adds it to the interface?

**Comment by Ryanf55** [comment]
> On Sun, 15 Dec 2024, Ryan wrote: No it doesn't. It wasn't hooked up.
> .... so maybe just comment out the code which adds it to the interface?

Ok, done.

**Review by peterbarker — APPROVED** [review]
OK, so that seems to have been in for a decade and not worked?!

**Comment by Ryanf55** [comment]
> OK, so that seems to have been in for a decade and not worked?!

Yep:) Just helping remove some of the footguns that other users have already reported.

**Pull request merged**
