### PR TITLE
live_graph_ui: fix drawing

### PR DESCRIPTION
**Pull request by khancyr**
Fix graphing in Ubuntu 18.04 both with python2 and python3, from matplotlib 2 to matplotlib 3

### CODE REVIEW

**Comment by tridge** [comment]
what is not working that this fixes? I've tested py2 and py3

**Comment by khancyr** [comment]
@tridge here is a video with pip release showing the issue, and the result with the patch : https://www.youtube.com/watch?v=NjawwXP-bRY&feature=youtu.be

I just remember that I am using wayland and not X11, it could also be the cause of the issue.

**Comment by tridge** [comment]
that video is completely black for me

> I just remember that I am using wayland and not X11, it could also be the cause of the issue.

ahh, could be. The reason I don't just apply this is I'd want to analyse CPU cost. The live graph code is very sensitive to small changes making a huge difference in CPU usage

**Comment by khancyr** [comment]
Working video ! ( f***************** wayland...) https://www.youtube.com/watch?v=DsDhM52XJQM&feature=youtu.be

**Comment by tridge** [comment]
ok. I looked at CPU usage and was disappointed to find high cpu usage with or without your patch in master at the moment. Darn!
Looks like there is some work to do there ...

**Comment by khancyr** [comment]
Close as merged in https://github.com/ArduPilot/MAVProxy/commit/f7f37efab6d097ea1f4b8d08223edbba907dbfb5

**Pull request closed without merging**
