### PR TITLE
WIP: Be able to specify multiple master links at once

### PR DESCRIPTION
**Pull request by araneg**
This will eventually allow users to issue commands to multiple vehicles at the same time, without having to switch between each. Effectively, multiple vehicles can be selected via the vehicle command.

Currently, this is a work in progress.

### CODE REVIEW

**Comment by tridge** [comment]
this is a really nice idea! Even better if you can add a vehicle to the list with right-click menu on the map

**Comment by tridge** [comment]
for more realtime discussions, try the new mavproxy channel on discord https://ardupilot.org/discord

**Comment by tridge** [comment]
I've since added the "alllinks" command, which allows you to send any command to all links (all vehicles)

**Comment by araneg** [comment]
Closing due to https://github.com/ArduPilot/MAVProxy/commit/986253c5b08f2d8b83208b291fcc3a48ac0b3011

**Pull request closed without merging**
