### PR TITLE
Wx3

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
I've been using this branch for a while.  it's actually a requirement for the latest version of CUAV to work properly.  So I definitely think we should merge this!

**Comment by amilcarlucas** [comment]
#421 seams to make some problems of this PR disappear. :)
Because I have it and I did not notice any issues.

**Comment by tridge** [comment]
in combination with the PR from @SamuelDudley this works for me, thanks!
pushed

**Comment by rmackay9** [comment]
Great, thanks very much!

**Pull request closed without merging**
