### PR TITLE
Chat: added password input field for api_key

### PR DESCRIPTION
**Pull request by adityaomar3**
Before input key field for api key was exposed
key_input_field_before

After changes input key field for api key 

key input field after

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @adityaomar3,

Thanks very much for this.  It's a small thing but I wonder if you could appeand, "chat: " onto the front of the commit title?  It's not big deal but if you look at our commit list you'll see we normally append the subsystem name or directory name to each commit to make it more clear what it affects.  To be clear, I mean the commit title not the PR title.

This is a habit the AP devs have gotten into especially on the flight code side because it makes backporting to earlier versions easier.  It's not really very important for MAVProxy but we do it anyway.  Txs!

After that change I'll merge.

**Comment by rmackay9** [comment]
I've marked this for the EU dev call, that's just so that we don't forget to merge it.

**Comment by rmackay9** [comment]
Hi @adityaomar3,

By the way, is there any change in behaviour if Enter is pressed instead of pressing the "Set" button?

I forgot to bring this up on the EUDevCall but I'll ping some of the other devs in the morning and we will merge it then.

**Comment by adityaomar3** [comment]
> Hi @adityaomar3,
> 
> By the way, is there any change in behaviour if Enter is pressed instead of pressing the "Set" button?
> 
> I forgot to bring this up on the EUDevCall but I'll ping some of the other devs in the morning and we will merge it then.

Thanks for the review, I checked, it actually broke the enter key feature.

**Comment by adityaomar3** [comment]
A small change was required, now it is working absolutely fine.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
