### PR TITLE
Module: Add server module

### PR DESCRIPTION
**Pull request by patrickelectric**
Add rest server:
`module load restserver`
`restserver start`
`restserver stop`
`restserver address 127.0.0.1:3333`

Allow information access via simple rest api:

image

image

image

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by davidbuzz** [comment]
@patrickelectric - doesn't MAVCesium already include a tornado webserver into mavproxy..?
look at https://github.com/ArduPilot/MAVProxy/tree/master/MAVProxy/modules and then go into the "mavproxy_cesium" folder you'll see the `__init__.py` for mavcesium includes a tornado server object called cesium_web_server , which presents JSON over http, among other things.

**Comment by patrickelectric** [comment]
@davidbuzz the objective is to provide a simple server to help users to integrate programs with the vehicle, MAVCesium appears to be a bit overkill for this specific thing, besides that, the project appears to be dead for more than 2 years.

**Comment by peterbarker** [comment]
`server` seems a little too generic / uninformative / undiscoverable.  How about `restserver`?

**Comment by stephendade** [comment]
Just tested this under Python3.6 / Windows10.

Only issue is with the `` server address 127.0.0.1:3333`` command, which does not appear to change the server's IP address or port.

Related, I get an error message if I try to change the address/port prior to ``server start``. Maybe change it so the current port and address are in the ``ServerModule`` class? That way when the ``RestServer`` is started it can just grab the correct address/port as arguments?

**Comment by patrickelectric** [comment]
@peterbarker changed to restserver.
@stephendade thank you for the test, I did some modifications in the end and probably missed to update some part of the code. I believe that everything is right now.

**Comment by patrickelectric** [comment]
@peterbarker ping

**Comment by peterbarker** [comment]
@stephendade OK to retest?

**Comment by stephendade** [comment]
Retested on Win10/Python3 - works very nicely now! 

@patrickelectric - are you able to add in some documentation (the ``gh-pages`` branch in this repo)?

**Comment by peterbarker** [comment]
@peterbarker merged this, thanks!  That doco would be really nice, too :-)

**Comment by patrickelectric** [comment]
Thanks !
I'll send a PR to update the documentation asap.

**Pull request merged**
