### PR TITLE
Dataflash_logger: add setting to automatically rotate logs on disarm

### PR DESCRIPTION
**Pull request by RickReeser**
This will make the dataflash-over-mavlink module automatically rotate logs when the vehicle disarms if the ArduPilot parameter `LOG_FILE_DSRMROT` is set. Tested with ArduCopter 3.6.9.

My change is pretty naive, so let me know if there's a smarter way to do this.

### CODE REVIEW

**Comment by peterbarker** [comment]
I do like the idea of having the option of rotating these logs on disarm, but perhaps this would be better done as a setting within the dataflash_logger module within mavproxy?

So

`dataflash_logger set rotate_on_disarm True`

I don't think there's a good reason to reuse the on-board configuration.

**Comment by RickReeser** [comment]
Yeah, I was waffling between using the FC param or a module setting. Module setting is better. Changed and committed.

**Comment by peterbarker** [comment]
@RickReeser Looks good, except for the commit list.  Could you squash the commits together into a singlet commit with a message starting with, "dataflash_logger: ", please?

**Comment by RickReeser** [comment]
Can you merge-n-squash? Won't have access to terminal for a while, and I can't squash with the browser.

**Comment by peterbarker** [comment]
@RickReeser rebased, squash, fixed minor whitespace issue, added good commit message and pushed in - thanks!

**Pull request closed without merging**
