### PR TITLE
Support loading and reloading modules with optional keyword arguments

### PR DESCRIPTION
**Pull request by SamuelDudley**
#### EDITED 07/12/2017

This PR adds the ability to supply optional keyword arguments to a module as they are loaded. If supported by the module it allows users to configure the module at the ``__init__`` stage.
The MAVCesium module really needs this ability in order to take a path to a user settings file. See https://github.com/SamuelDudley/MAVCesium/issues/21

This PR does not affect existing module functionality and handles errors gracefully when users attempt to supply keyword arguments to a module that does not support them.

**Example of usage:** ``module load cesium:{"config":"~/MAVProxy/mavcesium.ini","foo":10}``

If entered from the MAVProxy console the above string will load the cesium module and pass `{config:~/MAVProxy/mavcesium.ini, foo:10}` into the `__init__` method. 

The PR also supports passing keyword arguments to a module as you launch mavproxy. One can now pass multiple optional arguments to modules at launch.

**Example of usage:** `--load-module cesium:'{"config":"~/MAVProxy/mavcesium.ini","foo":10}'` 

The above launch argument would load the `cesium` module and pass `{config:~/MAVProxy/mavcesium.ini, foo:10}` into the `__init__` method.

**Supporting optional kwargs**
 **Note:** Existing modules not wanting to make use of this feature don't need to be modified

For the module to support the keyword arguments the following is needed (note the addition of **`**kwargs`**):

```
class ExampleKeywordModule(mp_module.MPModule):

    def __init__(self, mpstate, **kwargs):
        super(ExampleModule, self).__init__(mpstate, "example", "Example keyword module")
       
       # do something with the kwargs here
       for key, value in kwargs.iteritems():
            print "%s == %s" %(key,value)
        ....
        ....

def init(mpstate, **kwargs):
    '''initialise module'''
    return ExampleKeywordModule(mpstate, **kwargs)
````

### CODE REVIEW

**Comment by fnoop** [comment]
+1 This would be a great addition to modules in mavproxy.  Currently you can't run more than one instance of mavproxy if modules consume any resources like a port, as they will clash.  I'm sure there are many other uses that this would be useful as well :)

**Comment by amilcarlucas** [comment]
Yeap, the RTCM module would benefit from this.

**Comment by SamuelDudley** [comment]
Quick update: In the gitter channel there were issues pointed out with using `:` as the split point in the strings. For example `config=C:/some_windows_path/conf.ini` would break at the `:`. As python does a pretty good job of parsing json strings I'll modify the PR and have another attempt at the syntax for comment.

**Comment by SamuelDudley** [comment]
modified to support json format and rebased off master

**Comment by peterbarker** [comment]
Isn't it the case that JSON lacks an escape character?

**Comment by peterbarker** [comment]
OK, sorted things out.

I've incorporated this PR within https://github.com/ArduPilot/MAVProxy/pull/473 (it was the perfect thing, thanks!)

**Comment by SamuelDudley** [comment]
@peterbarker The lack of escape char is a limitation, but it just means the JSON has to be last. Not so much an issue for this PR but for #394 order will matter. e.g. `link add tcp:127.0.0.1:14550:{"label":"foo"}` will work but `link add tcp:127.0.0.1:{"label":"foo"}:14550` will not.

 __TL:DR__ everything after the first `:{` is assumed to be JSON _if_ the final char is `}`. 

Glad your finding it useful! :+1:

**Comment by SamuelDudley** [comment]
Merged with https://github.com/ArduPilot/MAVProxy/commit/b816e9fda96457aa7136b7a5e7e6ab2a1d35daab

**Comment by peterbarker** [comment]
On Tue, 2 Jan 2018, Samuel Dudley wrote:

> Merged with b816e9f

Thanks Samuel!

**Pull request closed without merging**
