### PR TITLE
Fix Live Graph for macOSX

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by njoubert** [comment]
I tested this PR, and it works great! Thanks @bugobliterator !

**Comment by peterbarker** [comment]
I've tested this on Linux - no worries.

I'm a little concerned about that `set_facecolor` thing; why is that present here?

@stephendade Does this work OK on Windows with the `set_facecolor` change?

**Comment by stephendade** [comment]
@peterbarker - all good on Windows

**Comment by bugobliterator** [comment]
@peterbarker the `set_facecolor` change is done because MAVProxy was throwing warning of deprecation with matplotlib 2.0.0.

**Comment by peterbarker** [comment]
@bugobliterator OK, without the set_facecolor, this patch is a shoe-in.

With it, I'm leery of breaking people's graphing if they are using older matplotlib.

Will things work if we use the deprecated function?

**Comment by njoubert** [comment]
@bugobliterator it'd be great if you can drop in your MAVExplorer patches into the same PR. As a primarily-mac user, it's **really powerful** to have all the utilities available on Mac!

**Comment by bugobliterator** [comment]
@peterbarker resurrecting this PR, I have made the change you requested.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request closed without merging**
